# Generated by Django 4.2.13 on 2024-11-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstance',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userinstance',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Отображаемое имя'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos', verbose_name='Фото профиля')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
