# Generated by Django 4.2.13 on 2024-11-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinstance_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinstance',
            managers=[
            ],
        ),
    ]
