# Generated by Django 4.2.13 on 2024-12-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userinstance_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstance',
            name='phone_number',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
